WIP: MkDocs documentation page
tweag/FawltyDeps pull request #449
Opened 2024-09-03 14:02 UTC by mknorps

```
mkdocs build
mkdocs serve
```

2024-09-16 13:12 UTC, jherland commented on pyproject.toml
Are these whitespace changes intentional and/or related to the rest of this PR?

2024-12-27 10:09 UTC, mknorps commented on pyproject.toml
Not really. This is an artifact of autoformatting. Disabled for now to minimize the change.

2025-01-07 20:14 UTC, jherland requested changes
Big review, lots of comments, but don't be discouraged! I love the look of the docs website, and I'm happy to help in any way I can to get this merged! ❤️

2025-01-07 20:14 UTC, jherland commented on .github/workflows/docs.yaml
> +            mkdocs-material-
Not sure what's going on here, the `date --utc '+%V'` prints the current week number, IIUC. Why is this appropriate as a cache key?

2025-01-07 20:14 UTC, jherland commented on .gitignore
> +site/
This is the default location used by mkdocs,  I assume? I don't see `site/` referenced anywhere else in these changes...

2025-01-07 20:14 UTC, jherland commented on .github/workflows/docs.yaml
> +      - run: mkdocs gh-deploy --force
Ideally, this should used the `docs` dependency group that you added to `pyproject.toml`? And even more ideally (and I can easily do this in a separate PR), we should wrap this is a Nox action, so that we can easily generate the docs locally too?

2025-02-03 17:52 UTC, mknorps commented on .github/workflows/docs.yaml
> +      - run: mkdocs gh-deploy --force
What do you mean? Does the same apply to the previous `with` key?

2025-02-03 17:55 UTC, mknorps commented on .github/workflows/docs.yaml
> +          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
The idea is to have a unique GitHub bot identity that does the commits.
We could use something like:
```   
    git config user.name "${{ github.actor }}"
    git config user.email "${{ github.actor }}@users.noreply.github.com"
```
But that means that the person who merged the PR to the main branch will be markes as the author of the commit for the docs branch.

We could also go a bit simpler, not marking the particular bot, but to say that we use a bot to generate this commit:
```
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
```

What do you think would be best?

2025-02-03 17:59 UTC, mknorps commented on .github/workflows/docs.yaml
> +            mkdocs-material-
This whole GitHub action is based on the mkdocs (Publishing your site)[https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions] guide. If you have some other idea for the cache key, we can change the current one.

2025-02-12 10:56 UTC, mknorps commented on mkdocs.yml
> +      permalink: true
Addressed in e0430245596c275459a2e0e48852d18a1d307d99

2025-02-12 10:56 UTC, mknorps commented on docs/reference.md
> +Run `fawltydeps --help` to get the full list of available options.
Addressed in e0430245596c275459a2e0e48852d18a1d307d99.

2025-02-12 10:58 UTC, mknorps commented on docs/reference.md
> +default behavior of FawltyDeps. Here's a fairly comprehensive example:
Addressed in e0430245596c275459a2e0e48852d18a1d307d99.

2025-02-12 13:19 UTC, jherland commented on docs/usage.md
> +See [Explanation](./explanation.md) for more details.
The `--help` text provided for these options should be short (so as not to overwhelm the user), but on this page I think we have room to provide a little more detail explaining why/when to use each of these command-line options:

```suggestion
### How to match `import` statements with declared dependencies 

When FawltyDeps analyzes undeclared and unused dependencies, it needs to match
`import` statements in your code with corresponding package dependencies
declared in your project configuration. We support the following options to help this process:

- `--pyenv`: Where to search for Python environments (e.g. virtualenvs) that have project dependencies installed. Finding installed dependencies is the best way to correctly match import names  and declared dependencies. If this is not given, the project directories will be searched for Python environments.
- `--custom-mapping-file`: A TOML file containing mapping of dependencies to import names defined by the user. When provided, this mapping takes precedence over looking through installed packages for a match. This is a power user feature for when you want full control of how FawltyDeps matches import names and package names.
- `--install-deps`: Allow FawltyDeps to auto-install declared dependencies into a separate temporary virtualenv to discover the imports they expose. This is potentially expensive, but it allows FawltyDeps to provide a good analysis when there is no existing Python environment with project dependencies installed.

For more details about the process of matching `import` statements to declared dependencies, please see the [Resolving dependencies section in Explanation](./explanation.md#resolving-dependencies).
```

2025-02-12 13:20 UTC, jherland commented on docs/reference.md
> +## Configuration
Looks good. Added some further suggestions in a separate comment.

2025-02-12 13:22 UTC, jherland commented on .github/workflows/docs.yaml
> +      - run: mkdocs gh-deploy --force
No, I just noticed GitHub flagging the lack of a newline at the end of the file:
![Screenshot_20250212_142145](https://github.com/user-attachments/assets/4355a2c5-3091-492b-93a8-ed813d21856e)

2025-02-12 13:33 UTC, jherland commented on .github/workflows/docs.yaml
> +          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
Maybe the last one, but I'm also happy to leave it as-is. Just curious about where this was coming from...

Thanks for the explanation! 🙏🏻

2025-02-12 14:03 UTC, jherland commented on .github/workflows/docs.yaml
> +            mkdocs-material-
Thanks for pointing to the source. From there I was able to find [this PR](https://github.com/squidfunk/mkdocs-material/pull/5463) which added the week number, and there is some discussion there about what is an appropriate cache key, and I guess this could even vary from project to project.

Anyway, this is a small detail that I'm happy to keep as it is for now.

2025-02-21 08:38 UTC, mknorps commented on .github/workflows/docs.yaml
> +          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
Sure :)
So let's leave the configuration as it. I added reference, so the source of this code is investigable.

2025-02-21 08:43 UTC, mknorps commented on .gitignore
> +site/
Yes, this is a default location when you are building the site locally.
The site is not referenced anywhere, because the GitHUb action for building and deploying the docs is building the documentation in a separate branch: https://github.com/tweag/FawltyDeps/tree/gh-pages, where only documentation sits.

2025-02-21 08:50 UTC, mknorps commented on docs/installation.md
> +Consider adding `fawltydeps` to your development dependencies, to help you catch undeclared and unused dependencies in your projects.
That is a great suggestion, thank you! You are setting up a good standard of the installation instruction 🙏

2025-02-21 08:52 UTC, mknorps commented on README.md
>  ![FawltyDeps demo](https://github.com/tweag/FawltyDeps/raw/main/docs/fawltydeps_demo_tqdm.gif)
Fixed in c77940756ef5c824403c99941ac096fcbdd407f2

2025-02-21 09:18 UTC, jherland commented on docs/CodeDesign.md
> +  a stable release, and are not yet End Of Life. Currently this is: v3.8 - v3.13.
After some more thinking, and [our discussion on Slack](https://moduscreate.slack.com/archives/C04AAQP8C85/p1740055300229949) I'm ready to change my mind on this: We only aim to support running current versions of Python, and improving support for older projects should be done via solutions outlined in #460.

Suggest:

```
- Support all current Python versions: that means [all Python versions that have
  a stable release, and are not yet End Of Life](https://devguide.python.org/versions/).
```

Or feel free to leave the patch as is and resolve this thread.

2025-02-21 14:57 UTC, mknorps commented on docs/CodeDesign.md
> +  a stable release, and are not yet End Of Life. Currently this is: v3.8 - v3.13.
How about this as a compromise:
```
- Support all current Python versions: that means [all Python versions that have
  a stable release, and are not yet End Of Life](https://devguide.python.org/versions/).
  - Currently we support running on Python v3.8 - v3.13.
  - Since we no longer rely on running inside the same Python environment as the project being
    analyzed, it is possible for us to support analyzing projects running on even older Python versions.
```
Without the promise of supporting the older versions, but gives hope that the user can check the code written in the older Python version anyway.

2025-02-21 15:09 UTC, mknorps commented on .github/workflows/docs.yaml
> +      - run: mkdocs gh-deploy --force
Using `docs` is implemented in 39db9b2f9bb3708bc6f40a6723d6bc0fdcd044e5.
Let's do the nox action in a separate PR. This one is already enormous 🙈

2025-02-21 15:33 UTC, mknorps commented on .github/workflows/docs.yaml
> +      - run: mkdocs gh-deploy --force
Updated in 072b290c322e02d5a012a1f52ec514a730349d2f

2025-02-21 15:44 UTC, mknorps commented on docs/images/fd_dependencies.png
The display updated in 90bc819b33595c940fd80c9a0f0364602449d0ed (It was stretching the pictures)

2025-02-21 18:49 UTC, jherland commented on docs/CodeDesign.md
> +  a stable release, and are not yet End Of Life. Currently this is: v3.8 - v3.13.
Ship it 😄

2025-02-21 19:18 UTC, jherland approved these changes
I took another look now, and except for two open questions (https://github.com/tweag/FawltyDeps/pull/449#discussion_r1905966505 and https://github.com/tweag/FawltyDeps/pull/449#discussion_r1905972035) I think this is ready to get merged. 🎉 

I also notice that the preview of the documentation page on https://tweag.github.io/FawltyDeps/ does not appear to be updated with the latest changes (for one, the menu structure on the left-hand side does not reflect the `nav` structure in `mkdocs.yml`).

2025-02-24 07:11 UTC, mknorps commented on docs/CodeDesign.md
> +  a stable release, and are not yet End Of Life. Currently this is: v3.8 - v3.13.
Done in a51776907f24e32419dff8708a6c82b60a10e4c4

2025-02-24 07:16 UTC, mknorps commented on docs/how_to_guides.md
Thanks, that was not the intention. I think I was caught in the middle of splitting our FAQ into the actual FAQ and how-to guides. In 1c3f177ae2c8f1419661c4b3caec3c1121f335f8 I did the split, and more entries are on the guide side. Please check the updated page: https://tweag.github.io/FawltyDeps

2025-02-24 07:19 UTC, mknorps commented on docs/FAQ.md
> +other dependencies are installed.
No longer needed, please see the comment in https://github.com/tweag/FawltyDeps/pull/449#discussion_r1905972035.

2025-02-24 11:11 UTC, jherland approved these changes
I noticed some misrendered lists in the new deployed docs. Otherwise, I think this is ready to merge. 🚀

2025-02-24 11:11 UTC, jherland commented on docs/CodeDesign.md
> +    analyzed, it is possible for us to support analyzing projects running on even older Python versions.
Same problem with mkdocs list rendering

```suggestion
- Support all current Python versions: that means [all Python versions that have
  a stable release, and are not yet End Of Life](https://devguide.python.org/versions/).
    - Currently we support running on Python v3.8 - v3.13.
    - Since we no longer rely on running inside the same Python environment as the project being
      analyzed, it is possible for us to support analyzing projects running on even older Python versions.
```

2025-02-24 11:11 UTC, jherland commented on docs/how_to_guides.md
Looks good now!

2025-02-24 11:11 UTC, jherland commented on docs/FAQ.md
> +other dependencies are installed.
Looks good now!

2025-02-25 07:48 UTC, merged